#!/bin/bash

cd $(dirname $0)

docker build -t indy-cat-run -f ../docker/Dockerfile.run .. || exit 1

ARGS=""
if [ -z "$PORTS" ]; then
	ARGS="-p 5000:5000 -p 10000-10050:10000-10050"
else
	for PORT in $PORTS; do
		ARGS="${ARGS} -p $PORT"
	done
fi

PTVSD_PORT="${PTVSD_PORT-5678}"
PYDEVD_PORT="${PYDEVD_PORT-18765}"

if [ ! -z "${ENABLE_PTVSD}" ] || [[ "$@" == *--debug-vs* ]]; then
	ARGS="${ARGS} -e ENABLE_PTVSD=\"${ENABLE_PTVSD}\""
fi

if [ ! -z "${ENABLE_PYDEVD}" ] || [[ "$@" == *--debug* ]]; then
	ARGS="${ARGS} -e ENABLE_PYDEVD=\"${ENABLE_PYDEVD}\" -e PYDEVD_PORT=${PYDEVD_PORT}"
fi

RAND_NAME=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
docker run --rm -ti --name "indy-cat-runner_${RAND_NAME}" $ARGS indy-cat-run "$@"
