#!/bin/bash

cd $(dirname $0)

docker build -t indy-cat-run -f ../docker/Dockerfile.run .. || exit 1

ARGS=""
for PORT in $PORTS; do
	ARGS="${ARGS} -p $PORT"
done

PTVSD_PORT="${PTVSD_PORT-5678}"

if [ ! -z "${ENABLE_PTVSD}" ] || [[ "$@" == *--debug* ]]; then
	ARGS="${ARGS} -e ENABLE_PTVSD=\"${ENABLE_PTVSD}\" -p $PTVSD_PORT:$PTVSD_PORT"
fi

RAND_NAME=$(cat /dev/urandom | env LC_CTYPE=C tr -dc 'a-zA-Z0-9' | fold -w 16 | head -n 1)
docker run --rm -ti --name "indy-cat-runner_${RAND_NAME}" $ARGS indy-cat-run "$@"
