FROM bcgovimages/aries-cloudagent:py36-1.16-1_1.0.0-rc0

USER root

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY ngrok-wait.sh ngrok-wait.sh
RUN chmod +x ./ngrok-wait.sh

USER $user

# temporary until this PR gets merged/released
RUN pip uninstall -y aries-cloudagent
RUN pip install aries-cloudagent[indy,bbs,askar]@git+https://github.com/ianco/aries-cloudagent-python@endorser-write-did
