# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-17 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.TextField(blank=True),
        ),
    ]
