# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credential',
            old_name='start_date',
            new_name='effective_date',
        ),
        migrations.RemoveField(
            model_name='credential',
            name='end_date',
        ),
        migrations.AddField(
            model_name='credential',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
