# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0003_auto_20180821_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credential',
            name='effective_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
