# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-24 23:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0005_auto_20180824_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='topics',
        ),
        migrations.AddField(
            model_name='credential',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api_v2.Topic'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topicrelationship',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api_v2.Credential'),
        ),
    ]
