# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-29 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0007_auto_20180827_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='related_topics',
        ),
        migrations.AddField(
            model_name='topic',
            name='related_to',
            field=models.ManyToManyField(related_name='related_from', through='api_v2.TopicRelationship', to='api_v2.Topic'),
        ),
    ]
