# Generated by Django 2.1.5 on 2019-02-01 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0023_name_type'),
        ('api_v2', '0023_issuer_endpoint'),
    ]

    operations = [
    ]
