# Generated by Django 2.1.7 on 2019-03-28 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0023_issuer_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('subscription_type', models.TextField(max_length=20)),
                ('topic_source_id', models.TextField(blank=True, null=True)),
                ('target_url', models.TextField(blank=True, max_length=240, null=True)),
                ('hook_token', models.TextField(blank=True, max_length=240, null=True)),
                ('credential_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='api_v2.CredentialType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='hook_token',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='org_name',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='target_url',
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
