# Generated by Django 2.1.8 on 2019-04-09 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0024_auto_20190328_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='credential_type',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hook_token',
        ),
        migrations.RemoveField(
            model_name='user',
            name='org_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='registration_expiry',
        ),
        migrations.RemoveField(
            model_name='user',
            name='target_url',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
