# uses ONBUILD instructions described here:
# https://github.com/gliderlabs/logspout/tree/master/custom

FROM gliderlabs/logspout:master@sha256:2d81c026e11ac67f7887029dbfd7d36ee986d946066b45c1dabd966278eb5681
ENV SYSLOG_FORMAT rfc3164
