# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("api_v2", "0006_auto_20180824_2333")]

    operations = [
        migrations.AlterField(
            model_name="topicrelationship",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="api_v2.Topic",
            ),
        )
    ]
