# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-21 17:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("api_v2", "0011_credentialtype_visible_fields")]

    operations = [
        migrations.AddField(
            model_name="credential",
            name="inactive",
            field=models.BooleanField(db_index=True, default=False),
        )
    ]
