# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-03 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0017_auto_20181113_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='last_issue_date',
            field=models.DateTimeField(null=True),
        ),
    ]
