# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-07 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0018_credentialtype_last_issue_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialtype',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
