# Generated by Django 2.1.5 on 2019-01-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0022_auto_20190109_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='endpoint',
            field=models.TextField(null=True),
        ),
    ]
