{{ $secretName := printf "%s-api" (include "common.names.fullname" .) }}
{{ $adminApiKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $secretName "Key" "adminApiKey" "Length" 32) }}
{{ $walletKey := include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" $secretName "Key" "walletKey" "Length" 32) }}
apiVersion: v1
kind: Secret
metadata:
  annotations:
    helm.sh/resource-policy: keep
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  name: {{ printf "%s-api" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- if not (index .Values "argfile.yml" "admin-insecure-mode") }}
  adminApiKey: {{ $adminApiKey }}
  {{- end }}
  walletKey: {{ $walletKey }}
