apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-seed" (include "common.names.fullname" .) }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: agent
  annotations:
    helm.sh/resource-policy: keep
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  seed: {{ include "getOrGeneratePass" (dict "Namespace" .Release.Namespace "Kind" "Secret" "Name" (printf "%s-seed" (include "common.names.fullname" .)) "Key" "seed" "Length" 32) }}
