{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "acapy.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: 
    app.kubernetes.io/component: agent
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
