 services:
  agency:
    image: acapy-test
    ports:
      - "3001:3001"
    command: >
      start
        --label Agency
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://agency:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name agency
        --wallet-key insecure
        --auto-provision
        --multitenant
        --multitenant-admin
        --jwt-secret insecure
        --multitenancy-config wallet_type=single-wallet-askar key_derivation_method=RAW
        --log-level info
        --debug-webhooks
        --notify-revocation
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5
    depends_on:
      tails:
        condition: service_started

  holder_anoncreds:
    image: acapy-test
    ports:
      - "3002:3001"
    command: >
      start
        --label Holder-AnonCreds
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://holder_anoncreds:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type askar-anoncreds
        --wallet-name holder_anoncreds
        --wallet-key insecure
        --auto-provision
        --log-level info
        --debug-webhooks
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  holder_indy:
    image: acapy-test
    ports:
      - "3003:3001"
    command: >
      start
        --label Holder-Indy
        --inbound-transport http 0.0.0.0 3000
        --outbound-transport http
        --endpoint http://holder_indy:3000
        --admin 0.0.0.0 3001
        --admin-insecure-mode
        --tails-server-base-url http://tails:6543
        --genesis-url http://test.bcovrin.vonx.io/genesis
        --wallet-type askar
        --wallet-name holder_indy
        --wallet-key insecure
        --auto-provision
        --log-level info
        --debug-webhooks
        --monitor-revocation-notification
    healthcheck:
      test: curl -s -o /dev/null -w '%{http_code}' "http://localhost:3001/status/live" | grep "200" > /dev/null
      start_period: 30s
      interval: 7s
      timeout: 5s
      retries: 5

  example:
    container_name: controller
    build:
      context: ../..
    environment:
      - AGENCY=http://agency:3001
      - HOLDER_ANONCREDS=http://holder_anoncreds:3001
      - HOLDER_INDY=http://holder_indy:3001
    volumes:
      - ./example.py:/usr/src/app/example.py:ro,z
    command: python -m example
    depends_on:
      agency:
        condition: service_healthy
      holder_anoncreds:
        condition: service_healthy
      holder_indy:
        condition: service_healthy

  tails:
    image: ghcr.io/bcgov/tails-server:latest
    ports:
      - 6543:6543
    environment:
      - GENESIS_URL=http://test.bcovrin.vonx.io/genesis
    command: >
      tails-server
      --host 0.0.0.0
      --port 6543
      --storage-path /tmp/tails-files
      --log-level INFO

