#!/bin/sh

cd $(dirname $0)

docker build -t indy-cat-test -f ../docker/Dockerfile.test .. || exit 1

# on Windows, docker run needs to be prefixed by winpty
if [[ "$OSTYPE" == "msys" ]]; then
  winpty docker run --rm -ti --name indy-cat-runner indy-cat-test "$@"
else
  docker run --rm -ti --name indy-cat-runner indy-cat-test "$@"
fi
