blank_issues_enabled: false
contact_links:
  - name: ACA-Py Documentation
    url: https://aca-py.org
    about: Check the docs before opening an issue
  - name: Community Discord
    url: https://discord.gg/openwalletfoundation
    about: Ask questions in the aca-py channel on the OpenWallet Foundation Discord Server 
