FROM python:3.9-slim-bullseye

ENV ENABLE_PTVSD 0

# For consistency with base images, include curl for healthchecks
RUN apt-get update && apt-get install -y curl && apt-get clean

RUN pip install --no-cache-dir poetry

RUN mkdir -p aries_cloudagent && touch aries_cloudagent/__init__.py
ADD pyproject.toml poetry.lock README.md ./
RUN mkdir -p log && chmod -R ug+rw log

RUN poetry install -E "askar bbs"

ADD . .

ENTRYPOINT ["/bin/bash", "-c", "poetry run aca-py \"$@\"", "--"]
