ARG python_version=3.6.13
FROM python:${python_version}-slim-buster

RUN apt-get update -y && \
	apt-get install -y --no-install-recommends \
	libsodium23 && \
    apt-get clean && \
	rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

ADD requirements*.txt ./

RUN pip3 install --no-cache-dir \
	-r requirements.txt \
	-r requirements.askar.txt \
	-r requirements.bbs.txt \
	-r requirements.dev.txt

ADD . .

ENTRYPOINT ["/bin/bash", "-c", "pytest \"$@\"", "--"]
