FROM faber-alice-demo

# Install bdd dependencies
RUN pip3 install --no-cache-dir -r demo/requirements.behave.txt

WORKDIR ./demo
ADD demo/multi_ledger_config_bdd.yml ./demo/multi_ledger_config.yml
RUN chmod a+w .
ENTRYPOINT ["behave"]
