FROM python:3.10-slim
ENV ENABLE_PTVSD 0

WORKDIR cloudagent
ADD aries_cloudagent ./aries_cloudagent
ADD requirements*.txt ./
ADD bin ./bin
ADD README.md ./
ADD setup.py ./
RUN pip install --upgrade pip && \
    pip install --no-cache-dir \
    -r requirements.txt \
    -r requirements.askar.txt \
    -r requirements.bbs.txt \
    -r requirements.globalid.txt \
    -e .

ENTRYPOINT ["aca-py"]
