ARG python_version=3.12.4
FROM python:${python_version}-slim-bookworm

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    libsodium23 git curl \
    build-essential \
    libsqlcipher-dev && \
    apt-get install -y libpq-dev postgresql-client && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN pip install --no-cache-dir uv

COPY ./README.md pyproject.toml ./
RUN mkdir acapy_agent && touch acapy_agent/__init__.py

ARG all_extras=0
RUN if [ "${all_extras}" != "0" ]; then uv sync --all-extras --group dev; else uv sync --extra didcommv2 --group dev; fi

COPY ./acapy_agent ./acapy_agent
COPY ./conftest.py ./

ENTRYPOINT ["/bin/bash", "-c", "uv run pytest \"$@\"", "--"]
