ARG python_version=3.12.4
FROM python:${python_version}-slim-bookworm

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends \
    libsodium23 git curl && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

RUN pip install --no-cache-dir poetry==2.1.1

COPY ./README.md pyproject.toml ./poetry.lock ./
RUN mkdir acapy_agent && touch acapy_agent/__init__.py

ARG all_extras=0
RUN if ! [ -z ${all_extras} ]; then poetry install --no-directory --all-extras --with=dev; else poetry install --no-directory -E "didcommv2" --with=dev; fi

COPY ./acapy_agent ./acapy_agent
COPY ./conftest.py ./

ENTRYPOINT ["/bin/bash", "-c", "poetry run pytest \"$@\"", "--"]
