FROM bcgovimages/von-image:py36-1.15-1
ADD delivery_service/kafka/outbound/requirements.txt requirements.txt
RUN pip3 install --no-cache-dir \
    -r requirements.txt
ADD delivery_service/kafka/outbound/service.py service.py
ENTRYPOINT ["python3", "./service.py"]
