"""JSON-LD, Linked Data Proof and Verifiable Credential constants"""

SECURITY_V1_URL = "https://w3id.org/security/v1"
SECURITY_V2_URL = "https://w3id.org/security/v2"
DID_V1_URL = "https://w3id.org/did/v1"
CREDENTIALS_ISSUER_URL = "https://www.w3.org/2018/credentials#issuer"
CREDENTIALS_V1_URL = "https://www.w3.org/2018/credentials/v1"
VERIFIABLE_CREDENTIAL_TYPE = "VerifiableCredential"
SECURITY_PROOF_URL = "https://w3id.org/security#proof"
SECURITY_SIGNATURE_URL = "https://w3id.org/security#signature"
SECURITY_BBS_URL = "https://w3id.org/security/bbs/v1"
