#!/bin/bash

shopt -s nocasematch

cd $(dirname $0)

AGENT=$1
if [[ $AGENT == "faber" ]] || [[ $AGENT == "alice" ]] || [[ $AGENT == "performance" ]]; then
	echo "Preparing agent image..."
	docker build -q -t faber-alice-demo -f ../docker/Dockerfile.demo .. || exit 1
else
  echo "Please specify which agent you want to run. Choose from 'faber', 'alice', or 'performance'.";
	exit 1;
fi

echo "Starting $AGENT..."
if [[ $AGENT == "faber" ]]; then
	AGENT_FILE="demo/faber-pg.py"
	AGENT_PORT=8020
	AGENT_PORT_RANGE=8020-8027
elif [[ $AGENT == "alice" ]]; then
	AGENT_FILE="demo/alice-pg.py"
	AGENT_PORT=8030
	AGENT_PORT_RANGE=8030-8037
else
	AGENT_FILE="demo/performance.py"
	AGENT_PORT=8030
	AGENT_PORT_RANGE=8030-8037
fi

DOCKER_ENV="-e LOG_LEVEL=${LOG_LEVEL} -e RUNMODE=docker"
if ! [ -z "$POSTGRES" ]; then
	DOCKER_ENV="${DOCKER_ENV} -e POSTGRES=1 -e RUST_BACKTRACE=1"
fi

# on Windows, docker run needs to be prefixed by winpty
if [[ "$OSTYPE" == "msys" ]]; then
	DOCKER="winpty docker"
else
	DOCKER=${DOCKER:-docker}
fi

$DOCKER run --name $AGENT --rm  -p 0.0.0.0:$AGENT_PORT_RANGE:$AGENT_PORT_RANGE $DOCKER_ENV -it faber-alice-demo $AGENT_FILE $AGENT_PORT
