#!/bin/bash

shopt -s nocasematch

cd $(dirname $0)

AGENT=$1
if [[ $AGENT == "faber" ]] || [[ $AGENT == "alice" ]] || [[ $AGENT == "acme" ]] || [[ $AGENT == "performance" ]]; then
	echo "Preparing agent image..."
	docker build -q -t faber-alice-demo -f ../docker/Dockerfile.demo .. || exit 1
else
	echo "Please specify which agent you want to run. Choose from 'faber', 'alice', 'acme', or 'performance'.";
	exit 1;
fi

echo "Starting $AGENT..."
if [[ $AGENT == "faber" ]]; then
	AGENT_MODULE="faber"
	AGENT_PORT=8020
	AGENT_PORT_RANGE=8020-8027
elif [[ $AGENT == "alice" ]]; then
	AGENT_MODULE="alice"
	AGENT_PORT=8030
	AGENT_PORT_RANGE=8030-8037
elif [[ $AGENT == "acme" ]]; then
	AGENT_MODULE="acme"
	AGENT_PORT=8040
	AGENT_PORT_RANGE=8040-8047
else
	AGENT_MODULE="performance"
	AGENT_PORT=8030
	AGENT_PORT_RANGE=8030-8037
fi

DOCKER_ENV="-e LOG_LEVEL=${LOG_LEVEL} -e RUNMODE=docker -e DOCKERHOST=`docker run --net=host codenvy/che-ip`"
if ! [ -z "$POSTGRES" ]; then
	DOCKER_ENV="${DOCKER_ENV} -e POSTGRES=1 -e RUST_BACKTRACE=1"
fi

# on Windows, docker run needs to be prefixed by winpty
if [[ "$OSTYPE" == "msys" ]]; then
	DOCKER="winpty docker"
fi
DOCKER=${DOCKER:-docker}

$DOCKER run --name $AGENT --rm -it \
	-p 0.0.0.0:$AGENT_PORT_RANGE:$AGENT_PORT_RANGE \
	$DOCKER_ENV \
	faber-alice-demo $AGENT_MODULE $AGENT_PORT
