#!/bin/bash

# external queue setup, if needed
inboundQueueArgs=()
outboundQueueArgs=()
ENABLE_REDIS_INBOUND=0
ENABLE_KAFKA_INBOUND=0
ENABLE_REDIS_OUTBOUND=0
ENABLE_KAFKA_OUTBOUND=0
REDIS_INBOUND_CLASS_KEYWORD="RedisInboundQueue"
KAFKA_INBOUND_CLASS_KEYWORD="KafkaInboundQueue"
REDIS_OUTBOUND_CLASS_KEYWORD="RedisOutboundQueue"
KAFKA_OUTBOUND_CLASS_KEYWORD="KafkaOutboundQueue"
declare -a acapyArgs=($@)
for (( i = 0; i < ${#acapyArgs[*]}; ++ i ))
do
  	# outbound transport queue
	if [[ "${acapyArgs[$i]}" == "--outbound-queue-class" || "${acapyArgs[$i]}" == "-oqc" ]]; then
    if echo "${acapyArgs[$i+1]}" | grep -q "$REDIS_OUTBOUND_CLASS_KEYWORD"; then
      ENABLE_REDIS_OUTBOUND=1
      ENABLE_KAFKA_OUTBOUND=0
    fi
    if echo "${acapyArgs[$i+1]}" | grep -q "$KAFKA_OUTBOUND_CLASS_KEYWORD"; then
      ENABLE_REDIS_OUTBOUND=0
      ENABLE_KAFKA_OUTBOUND=1
    fi
	fi
	if [[ "${acapyArgs[$i]}" == "--outbound-queue" || "${acapyArgs[$i]}" == "-oq" ]]; then
		outboundQueueArgs+=("${acapyArgs[$i]}")
		outboundQueueArgs+=("${acapyArgs[$i+1]}")
	fi
	if [[ "${acapyArgs[$i]}" == "--outbound-queue-prefix" || "${acapyArgs[$i]}" == "-oqp" ]]; then
		outboundQueueArgs+=("${acapyArgs[$i]}")
		outboundQueueArgs+=("${acapyArgs[$i+1]}")
	fi
	# inbound transport queue
	if [[ "${acapyArgs[$i]}" == "--inbound-queue-class" || "${acapyArgs[$i]}" == "-iqc" ]]; then
		if echo "${acapyArgs[$i+1]}" | grep -q "$REDIS_INBOUND_CLASS_KEYWORD"; then
      ENABLE_REDIS_INBOUND=1
      ENABLE_KAFKA_INBOUND=0
    fi
    if echo "${acapyArgs[$i+1]}" | grep -q "$KAFKA_INBOUND_CLASS_KEYWORD"; then
      ENABLE_REDIS_INBOUND=0
      ENABLE_KAFKA_INBOUND=1
    fi
	fi
	if [[ "${acapyArgs[$i]}" == "--inbound-queue" || "${acapyArgs[$i]}" == "-iq" ]]; then
		inboundQueueArgs+=("${acapyArgs[$i]}")
		inboundQueueArgs+=("${acapyArgs[$i+1]}")
	fi
	if [[ "${acapyArgs[$i]}" == "--inbound-queue-prefix" || "${acapyArgs[$i]}" == "-iqp" ]]; then
		inboundQueueArgs+=("${acapyArgs[$i]}")
		inboundQueueArgs+=("${acapyArgs[$i+1]}")
	fi
	if [[ "${acapyArgs[$i]}" == "--inbound-transport" || "${acapyArgs[$i]}" == "-it" ]]; then
		inboundQueueArgs+=("${acapyArgs[$i]}")
		inboundQueueArgs+=("${acapyArgs[$i+1]}")
		inboundQueueArgs+=("${acapyArgs[$i+2]}")
		inboundQueueArgs+=("${acapyArgs[$i+3]}")
	fi
	if [[ "${acapyArgs[$i]}" == "--plugin-config" ]]; then
		inboundQueueArgs+=("${acapyArgs[$i]}")
		inboundQueueArgs+=("${acapyArgs[$i+1]}")
		outboundQueueArgs+=("${acapyArgs[$i]}")
		outboundQueueArgs+=("${acapyArgs[$i+1]}")
	fi
done
if [[ "$ENABLE_REDIS_INBOUND" == 1 ]]; then
  echo "Starting Redis Inbound Message Service."
  . ../delivery_service/redis/inbound/scripts/run.sh ${inboundQueueArgs[@]}
fi
if [[ "$ENABLE_KAFKA_INBOUND" == 1 ]]; then
  echo "Starting Kafka Inbound Message Service."
  . ../delivery_service/kafka/inbound/scripts/run.sh ${inboundQueueArgs[@]}
fi
if [[ "$ENABLE_REDIS_OUTBOUND" == 1 ]]; then
  echo "Starting Redis Outbound Message Service."
  . ../delivery_service/redis/outbound/scripts/run.sh ${outboundQueueArgs[@]}
fi
if [[ $ENABLE_KAFKA_OUTBOUND = 1 ]]; then
  echo "Starting Kafka Outbound Message Service."
  . ../delivery_service/kafka/outbound/scripts/run.sh ${outboundQueueArgs[@]}
fi
