name: "Run Aca-Py Integration Tests"
description: "Run integration tests for Aca-Py"
author: "iancostanzo@gmail.com"
inputs:
  TEST_SCOPE:
    description: "Set of flags that defines the test scope"
    required: false
    default: "-t @GHA"
runs:
  using: "composite"
  steps:
    - name: run-integration-tests-acapy
      # run: LEDGER_URL=http://test.bcovrin.vonx.io PUBLIC_TAILS_URL=https://tails.vonx.io ./run_bdd ${{ inputs.TEST_SCOPE }}
      run: ./run_bdd ${{ inputs.TEST_SCOPE }}
      shell: bash
      env:
        NO_TTY: "1"
      working-directory: acapy/demo
branding:
  icon: "mic"
  color: "purple"
