@startuml

package orgbook.rest {
  package orgbook.rest.indy {
  }

  package orgbook.rest.search {
  }

  orgbook.rest.indy -[hidden]right- orgbook.rest.search
}

package orgbook.views {
  package orgbook.views.indy

  package orgbook.views.orgbook

  orgbook.views.indy -[hidden]right- orgbook.views.orgbook
}

orgbook.rest.indy -down-> orgbook.views.indy
orgbook.rest.search -down-> orgbook.views.orgbook

package orgbook.api.indy {
  package orgbook.api.indy.indy
  note left
  * credential_offer
  * proof
  end note

  package orgbook.api.indy.orgbook
  note right
  * issuer
  * credential
  * proof_request
  end note

  orgbook.api.indy.indy -[hidden]right- orgbook.api.indy.orgbook
}

orgbook.views.indy -down-> orgbook.api.indy.indy
orgbook.views.indy -down-> orgbook.api.indy.orgbook

package vonx.von.indy

package orgbook.orgbook {
  package orgbook.models

  package orgbook.feedback

  package orgbook.utils
}

orgbook.api.indy.indy -down-> vonx.von.indy
orgbook.views.orgbook -down-> orgbook.models

vonx.von.indy -[hidden]right- orgbook.orgbook
orgbook.models -[hidden]right- orgbook.feedback
orgbook.feedback -[hidden]right- orgbook.utils

orgbook.api.indy.orgbook -down-> orgbook.models

@enduml
