FROM bcgovimages/von-image:py36-1.9-0

RUN mkdir src test-reports

WORKDIR /home/indy/src

ADD requirements.txt requirements.dev.txt ./

RUN pip3 install --no-cache-dir \
	-r requirements.txt \
	-r requirements.dev.txt \
	pytest

ADD . .

ENTRYPOINT ["/bin/bash", "-c", "pytest \"$@\"", "--"]