FROM bcgovimages/von-image:py36-1.8-0

ADD requirements.txt requirements.dev.txt ./

RUN pip3 install --no-cache-dir \
	-r requirements.txt \
	-r requirements.dev.txt \
	pytest

ADD . .

CMD [ "pytest" ]
